export const SAMPLE_FALLBACKS = {
    overview_daily_cards: [
        {
            period: 'daily',
            card_key: 'brand_revenue',
            label: '어제(최근 확정일) 브랜드 매출',
            value: '914000',
            delta: '0.01668520578420467',
            reason: '매출 차이가 크지 않으므로 역할 관측 상태와 집중도에서 우선 점검 대상을 좁히는 편이 안전합니다.',
            as_of_date: '2024-05-10',
            support_window_days: '1'
        },
        {
            period: 'daily',
            card_key: 'active_products',
            label: '활성 상품 수',
            value: '4',
            delta: '',
            reason: '활성 정의는 판매 발생 상품 기준입니다. 노출/판매중 상태와 혼용하지 않습니다.',
            as_of_date: '2024-05-10',
            support_window_days: '1'
        },
        {
            period: 'daily',
            card_key: 'pgm_coverage',
            label: 'PGM 관측 커버리지',
            value: '0.5',
            delta: '',
            reason: '동일 일자 역할 스냅샷이 없는 상품은 mart에서 blank로 남기고 view_model/UI에서는 관측 상태 없음으로만 읽힙니다.',
            as_of_date: '2024-05-10',
            support_window_days: '1'
        },
        {
            period: 'daily',
            card_key: 'top_share',
            label: '상위 상품 매출 비중',
            value: '0.47702407002188185',
            delta: '',
            reason: '매출 집중도는 일별 운영 리스크를 읽는 최소 지표입니다.',
            as_of_date: '2024-05-10',
            support_window_days: '1'
        }
    ],
    overview_weekly_cards: [
        {
            period: 'weekly',
            card_key: 'revenue_7d',
            label: '직전 7일 매출',
            value: '6142000',
            delta: '2.772727272727273',
            reason: '기준일 당일을 제외한 직전 7일 누적 매출입니다.',
            as_of_date: '2024-05-10',
            support_window_days: '7'
        },
        {
            period: 'weekly',
            card_key: 'revenue_30d_reference',
            label: '직전 30일 참조 매출',
            value: '7770000',
            delta: '',
            reason: '일별 판단은 7일 중심으로 보고, 30일은 보조 참조 구간으로 사용합니다.',
            as_of_date: '2024-05-10',
            support_window_days: '30'
        },
        {
            period: 'weekly',
            card_key: 'dominant_role',
            label: '매출 기여 주 역할',
            value: 'expansion',
            delta: '',
            reason: '매출 기준 중심 역할을 먼저 보고, 구조 리스크는 집중도로 함께 확인합니다.',
            as_of_date: '2024-05-10',
            support_window_days: '7'
        },
        {
            period: 'weekly',
            card_key: 'status_label',
            label: '주간 상태 요약',
            value: '매출은 유지 중이고 구조 확인이 필요한 상태입니다.',
            delta: '',
            reason: '매출 차이가 크지 않으므로 역할 관측 상태와 집중도에서 우선 점검 대상을 좁히는 편이 안전합니다.',
            as_of_date: '2024-05-10',
            support_window_days: '7'
        }
    ],
    overview_monthly_cards: [
        {
            period: 'monthly',
            card_key: 'revenue_30d',
            label: '직전 30일 매출',
            value: '7770000',
            delta: '',
            reason: '기준일 당일을 제외한 직전 30일 누적 매출입니다.',
            as_of_date: '2024-05-10',
            support_window_days: '30'
        },
        {
            period: 'monthly',
            card_key: 'revenue_90d_reference',
            label: '직전 90일 참조 매출',
            value: '7770000',
            delta: '',
            reason: '월간 해석은 30일을 본체로 보고, 90일은 구조 비교용 보조 참조 구간으로 사용합니다.',
            as_of_date: '2024-05-10',
            support_window_days: '90'
        },
        {
            period: 'monthly',
            card_key: 'top_share',
            label: '상위 상품 집중도',
            value: '0.47702407002188185',
            delta: '',
            reason: '집중도가 높으면 단기 매출이 좋아도 구조 리스크로 해석합니다.',
            as_of_date: '2024-05-10',
            support_window_days: '30'
        },
        {
            period: 'monthly',
            card_key: 'coverage',
            label: '역할 관측 안정도',
            value: '0.5',
            delta: '',
            reason: '관측 상태 없음 유지 원칙은 당일 관측 공백을 그대로 드러내기 위한 안전장치이며 최신 역할로 보정하지 않습니다.',
            as_of_date: '2024-05-10',
            support_window_days: '30'
        }
    ],
    overview_revenue_story: [
        {
            period: 'daily',
            period_label: '어제(최근 확정일)',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_revenue: '2714300',
            previous_revenue: '2697500',
            revenue_delta: '16800',
            revenue_delta_rate: '0.0062279888785912885',
            lead_role_state_primary: 'entry',
            lead_role_label: '첫구매 유도',
            lead_role_revenue_share: '0.31871937516118337',
            swing_role_state_primary: 'entry',
            swing_role_label: '첫구매 유도',
            swing_role_delta_revenue: '865100',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true',
            current_coverage_rate: '1',
            previous_coverage_rate: '0',
            coverage_summary: '역할 이력 커버리지는 현재 1/1일, 비교 구간 0/1일입니다.',
            history_warning_copy: '역할 이력 커버리지는 현재 1/1일, 비교 구간 0/1일입니다. 매출 자체는 실매출 기준으로 보고, 역할 변화 해석은 실제 관측된 날짜 범위 안에서만 읽어 주세요.',
            truth_source: 'brand_window_snapshot',
            story_headline: '어제(최근 확정일) 실매출은 전체 합계로 집계했고 역할 해석은 가용 역할 관측 기준으로 첫구매 유도 축을 먼저 확인합니다.',
            story_note: '역할 이력 커버리지는 현재 1/1일, 비교 구간 0/1일입니다. 매출 자체는 실매출 기준으로 보고, 역할 변화 해석은 실제 관측된 날짜 범위 안에서만 읽어 주세요. 기간 총매출과 역할 변화 해석은 같은 의미가 아닙니다.'
        },
        {
            period: 'weekly',
            period_label: '최근 7일',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_revenue: '21632800',
            previous_revenue: '34582300',
            revenue_delta: '-12949500',
            revenue_delta_rate: '-0.3744545620158289',
            lead_role_state_primary: 'entry',
            lead_role_label: '첫구매 유도',
            lead_role_revenue_share: '0.31871937516118337',
            swing_role_state_primary: 'entry',
            swing_role_label: '첫구매 유도',
            swing_role_delta_revenue: '865100',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true',
            current_coverage_rate: '0.14285714285714285',
            previous_coverage_rate: '0',
            coverage_summary: '역할 이력 커버리지는 현재 1/7일, 비교 구간 0/7일입니다.',
            history_warning_copy: '역할 이력 커버리지는 현재 1/7일, 비교 구간 0/7일입니다. 매출 자체는 실매출 기준으로 보고, 역할 변화 해석은 실제 관측된 날짜 범위 안에서만 읽어 주세요.',
            truth_source: 'brand_window_snapshot',
            story_headline: '최근 7일 실매출은 전체 합계로 집계했고 역할 해석은 가용 역할 관측 기준으로 첫구매 유도 축을 먼저 확인합니다.',
            story_note: '역할 이력 커버리지는 현재 1/7일, 비교 구간 0/7일입니다. 매출 자체는 실매출 기준으로 보고, 역할 변화 해석은 실제 관측된 날짜 범위 안에서만 읽어 주세요. 기간 총매출과 역할 변화 해석은 같은 의미가 아닙니다.'
        },
        {
            period: 'monthly',
            period_label: '최근 30일',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_revenue: '158531220',
            previous_revenue: '174996100',
            revenue_delta: '-16464880',
            revenue_delta_rate: '-0.09408712537022254',
            lead_role_state_primary: 'entry',
            lead_role_label: '첫구매 유도',
            lead_role_revenue_share: '0.31871937516118337',
            swing_role_state_primary: 'entry',
            swing_role_label: '첫구매 유도',
            swing_role_delta_revenue: '865100',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true',
            current_coverage_rate: '0.03333333333333333',
            previous_coverage_rate: '0',
            coverage_summary: '역할 이력 커버리지는 현재 1/30일, 비교 구간 0/30일입니다.',
            history_warning_copy: '역할 이력 커버리지는 현재 1/30일, 비교 구간 0/30일입니다. 매출 자체는 실매출 기준으로 보고, 역할 변화 해석은 실제 관측된 날짜 범위 안에서만 읽어 주세요.',
            truth_source: 'brand_window_snapshot',
            story_headline: '최근 30일 실매출은 전체 합계로 집계했고 역할 해석은 가용 역할 관측 기준으로 첫구매 유도 축을 먼저 확인합니다.',
            story_note: '역할 이력 커버리지는 현재 1/30일, 비교 구간 0/30일입니다. 매출 자체는 실매출 기준으로 보고, 역할 변화 해석은 실제 관측된 날짜 범위 안에서만 읽어 주세요. 기간 총매출과 역할 변화 해석은 같은 의미가 아닙니다.'
        }
    ],
    overview_role_delta: [
        {
            period: 'daily',
            role_state_primary: 'entry',
            role_label: '첫구매 유도',
            current_revenue: '865100',
            previous_revenue: '0',
            revenue_delta: '865100',
            revenue_delta_rate: '',
            current_revenue_share: '0.31871937516118337',
            previous_revenue_share: '0',
            revenue_share_delta: '0.31871937516118337',
            role_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true'
        },
        {
            period: 'daily',
            role_state_primary: 'expansion',
            role_label: '단골 유도',
            current_revenue: '864500',
            previous_revenue: '0',
            revenue_delta: '864500',
            revenue_delta_rate: '',
            current_revenue_share: '0.3184983236930332',
            previous_revenue_share: '0',
            revenue_share_delta: '0.3184983236930332',
            role_rank: '2',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true'
        },
        {
            period: 'daily',
            role_state_primary: 'return',
            role_label: '반복 구매',
            current_revenue: '479500',
            previous_revenue: '0',
            revenue_delta: '479500',
            revenue_delta_rate: '',
            current_revenue_share: '0.1766569649633423',
            previous_revenue_share: '0',
            revenue_share_delta: '0.1766569649633423',
            role_rank: '3',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true'
        },
        {
            period: 'daily',
            role_state_primary: '',
            role_label: '관측 상태 없음',
            current_revenue: '345700',
            previous_revenue: '0',
            revenue_delta: '345700',
            revenue_delta_rate: '',
            current_revenue_share: '0.12736248756585491',
            previous_revenue_share: '0',
            revenue_share_delta: '0.12736248756585491',
            role_rank: '4',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true'
        },
        {
            period: 'daily',
            role_state_primary: 'convergence',
            role_label: '구매 집중',
            current_revenue: '159500',
            previous_revenue: '0',
            revenue_delta: '159500',
            revenue_delta_rate: '',
            current_revenue_share: '0.058762848616586226',
            previous_revenue_share: '0',
            revenue_share_delta: '0.058762848616586226',
            role_rank: '5',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true'
        },
        {
            period: 'weekly',
            role_state_primary: 'entry',
            role_label: '첫구매 유도',
            current_revenue: '865100',
            previous_revenue: '0',
            revenue_delta: '865100',
            revenue_delta_rate: '',
            current_revenue_share: '0.31871937516118337',
            previous_revenue_share: '0',
            revenue_share_delta: '0.31871937516118337',
            role_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true'
        },
        {
            period: 'weekly',
            role_state_primary: 'expansion',
            role_label: '단골 유도',
            current_revenue: '864500',
            previous_revenue: '0',
            revenue_delta: '864500',
            revenue_delta_rate: '',
            current_revenue_share: '0.3184983236930332',
            previous_revenue_share: '0',
            revenue_share_delta: '0.3184983236930332',
            role_rank: '2',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true'
        },
        {
            period: 'weekly',
            role_state_primary: 'return',
            role_label: '반복 구매',
            current_revenue: '479500',
            previous_revenue: '0',
            revenue_delta: '479500',
            revenue_delta_rate: '',
            current_revenue_share: '0.1766569649633423',
            previous_revenue_share: '0',
            revenue_share_delta: '0.1766569649633423',
            role_rank: '3',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true'
        },
        {
            period: 'weekly',
            role_state_primary: '',
            role_label: '관측 상태 없음',
            current_revenue: '345700',
            previous_revenue: '0',
            revenue_delta: '345700',
            revenue_delta_rate: '',
            current_revenue_share: '0.12736248756585491',
            previous_revenue_share: '0',
            revenue_share_delta: '0.12736248756585491',
            role_rank: '4',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true'
        },
        {
            period: 'weekly',
            role_state_primary: 'convergence',
            role_label: '구매 집중',
            current_revenue: '159500',
            previous_revenue: '0',
            revenue_delta: '159500',
            revenue_delta_rate: '',
            current_revenue_share: '0.058762848616586226',
            previous_revenue_share: '0',
            revenue_share_delta: '0.058762848616586226',
            role_rank: '5',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true'
        },
        {
            period: 'monthly',
            role_state_primary: 'entry',
            role_label: '첫구매 유도',
            current_revenue: '865100',
            previous_revenue: '0',
            revenue_delta: '865100',
            revenue_delta_rate: '',
            current_revenue_share: '0.31871937516118337',
            previous_revenue_share: '0',
            revenue_share_delta: '0.31871937516118337',
            role_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true'
        },
        {
            period: 'monthly',
            role_state_primary: 'expansion',
            role_label: '단골 유도',
            current_revenue: '864500',
            previous_revenue: '0',
            revenue_delta: '864500',
            revenue_delta_rate: '',
            current_revenue_share: '0.3184983236930332',
            previous_revenue_share: '0',
            revenue_share_delta: '0.3184983236930332',
            role_rank: '2',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true'
        },
        {
            period: 'monthly',
            role_state_primary: 'return',
            role_label: '반복 구매',
            current_revenue: '479500',
            previous_revenue: '0',
            revenue_delta: '479500',
            revenue_delta_rate: '',
            current_revenue_share: '0.1766569649633423',
            previous_revenue_share: '0',
            revenue_share_delta: '0.1766569649633423',
            role_rank: '3',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true'
        },
        {
            period: 'monthly',
            role_state_primary: '',
            role_label: '관측 상태 없음',
            current_revenue: '345700',
            previous_revenue: '0',
            revenue_delta: '345700',
            revenue_delta_rate: '',
            current_revenue_share: '0.12736248756585491',
            previous_revenue_share: '0',
            revenue_share_delta: '0.12736248756585491',
            role_rank: '4',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true'
        },
        {
            period: 'monthly',
            role_state_primary: 'convergence',
            role_label: '구매 집중',
            current_revenue: '159500',
            previous_revenue: '0',
            revenue_delta: '159500',
            revenue_delta_rate: '',
            current_revenue_share: '0.058762848616586226',
            previous_revenue_share: '0',
            revenue_share_delta: '0.058762848616586226',
            role_rank: '5',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true'
        }
    ],
    overview_role_drilldown: [
        {
            period: 'daily',
            role_state_primary: 'entry',
            role_label: '첫구매 유도',
            product_id: '1000000064',
            product_name: '2색 이티',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000064/image/list/1000000064_list_053.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000064',
            current_revenue: '600500',
            previous_revenue: '0',
            revenue_delta: '600500',
            revenue_delta_rate: '',
            current_share_in_role: '0.6941394058490348',
            current_share_in_period: '0.22123567770695943',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true'
        },
        {
            period: 'daily',
            role_state_primary: 'expansion',
            role_label: '단골 유도',
            product_id: '1000000094',
            product_name: '매화 3송이 1호',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000094/image/list/1000000094_list_039.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000094',
            current_revenue: '390000',
            previous_revenue: '0',
            revenue_delta: '390000',
            revenue_delta_rate: '',
            current_share_in_role: '0.45112781954887216',
            current_share_in_period: '0.14368345429760895',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true'
        },
        {
            period: 'daily',
            role_state_primary: 'return',
            role_label: '반복 구매',
            product_id: '1000000044',
            product_name: '고구마찰떡',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000044/image/list/1000000044_list_088.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000044',
            current_revenue: '199000',
            previous_revenue: '0',
            revenue_delta: '199000',
            revenue_delta_rate: '',
            current_share_in_role: '0.41501564129301355',
            current_share_in_period: '0.07331540360313893',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true'
        },
        {
            period: 'daily',
            role_state_primary: '',
            role_label: '관측 상태 없음',
            product_id: '1000000113',
            product_name: '매화 5송이 3호',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000113/image/list/1000000113_list_070.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000113',
            current_revenue: '167700',
            previous_revenue: '0',
            revenue_delta: '167700',
            revenue_delta_rate: '',
            current_share_in_role: '0.48510269019380964',
            current_share_in_period: '0.06178388534797185',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '1',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '1',
            partial_history_flag: 'true'
        },
        {
            period: 'weekly',
            role_state_primary: 'entry',
            role_label: '첫구매 유도',
            product_id: '1000000064',
            product_name: '2색 이티',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000064/image/list/1000000064_list_053.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000064',
            current_revenue: '600500',
            previous_revenue: '0',
            revenue_delta: '600500',
            revenue_delta_rate: '',
            current_share_in_role: '0.6941394058490348',
            current_share_in_period: '0.22123567770695943',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true'
        },
        {
            period: 'weekly',
            role_state_primary: 'expansion',
            role_label: '단골 유도',
            product_id: '1000000094',
            product_name: '매화 3송이 1호',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000094/image/list/1000000094_list_039.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000094',
            current_revenue: '390000',
            previous_revenue: '0',
            revenue_delta: '390000',
            revenue_delta_rate: '',
            current_share_in_role: '0.45112781954887216',
            current_share_in_period: '0.14368345429760895',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true'
        },
        {
            period: 'weekly',
            role_state_primary: 'return',
            role_label: '반복 구매',
            product_id: '1000000044',
            product_name: '고구마찰떡',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000044/image/list/1000000044_list_088.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000044',
            current_revenue: '199000',
            previous_revenue: '0',
            revenue_delta: '199000',
            revenue_delta_rate: '',
            current_share_in_role: '0.41501564129301355',
            current_share_in_period: '0.07331540360313893',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true'
        },
        {
            period: 'weekly',
            role_state_primary: '',
            role_label: '관측 상태 없음',
            product_id: '1000000113',
            product_name: '매화 5송이 3호',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000113/image/list/1000000113_list_070.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000113',
            current_revenue: '167700',
            previous_revenue: '0',
            revenue_delta: '167700',
            revenue_delta_rate: '',
            current_share_in_role: '0.48510269019380964',
            current_share_in_period: '0.06178388534797185',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '7',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '7',
            partial_history_flag: 'true'
        },
        {
            period: 'monthly',
            role_state_primary: 'entry',
            role_label: '첫구매 유도',
            product_id: '1000000064',
            product_name: '2색 이티',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000064/image/list/1000000064_list_053.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000064',
            current_revenue: '600500',
            previous_revenue: '0',
            revenue_delta: '600500',
            revenue_delta_rate: '',
            current_share_in_role: '0.6941394058490348',
            current_share_in_period: '0.22123567770695943',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true'
        },
        {
            period: 'monthly',
            role_state_primary: 'expansion',
            role_label: '단골 유도',
            product_id: '1000000094',
            product_name: '매화 3송이 1호',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000094/image/list/1000000094_list_039.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000094',
            current_revenue: '390000',
            previous_revenue: '0',
            revenue_delta: '390000',
            revenue_delta_rate: '',
            current_share_in_role: '0.45112781954887216',
            current_share_in_period: '0.14368345429760895',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true'
        },
        {
            period: 'monthly',
            role_state_primary: 'return',
            role_label: '반복 구매',
            product_id: '1000000044',
            product_name: '고구마찰떡',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000044/image/list/1000000044_list_088.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000044',
            current_revenue: '199000',
            previous_revenue: '0',
            revenue_delta: '199000',
            revenue_delta_rate: '',
            current_share_in_role: '0.41501564129301355',
            current_share_in_period: '0.07331540360313893',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true'
        },
        {
            period: 'monthly',
            role_state_primary: '',
            role_label: '관측 상태 없음',
            product_id: '1000000113',
            product_name: '매화 5송이 3호',
            image_url: 'https://godomall.speedycdn.net/a1ce4a197810c4cd52677b215337ca9e/goods/1000000113/image/list/1000000113_list_070.jpg',
            detail_url: 'https://kricecake.com/goods/goods_view.php?goodsNo=1000000113',
            current_revenue: '167700',
            previous_revenue: '0',
            revenue_delta: '167700',
            revenue_delta_rate: '',
            current_share_in_role: '0.48510269019380964',
            current_share_in_period: '0.06178388534797185',
            previous_share_in_role: '0',
            product_rank: '1',
            as_of_date: '2026-04-17',
            support_window_days: '30',
            current_covered_days: '1',
            previous_covered_days: '0',
            expected_window_days: '30',
            partial_history_flag: 'true'
        }
    ],
    product_table: [
        {
            product_id: 'p-101',
            product_name: 'Hydra Serum',
            product_name_source: 'product_master',
            profile_role_primary: 'entry',
            profile_role_secondary: 'expansion',
            profile_confidence: '0.92',
            role_state_primary: 'expansion',
            role_state_confidence: '0.86',
            pgm_observed_flag: 'true',
            role_state_source: 'same_date_snapshot',
            revenue: '436000',
            order_count: '7',
            quantity: '7',
            revenue_share_in_brand_day: '0.47702407002188185',
            revenue_rank_in_brand_day: '1',
            revenue_7d: '2517000',
            revenue_30d: '3089000',
            revenue_90d: '3089000',
            revenue_day_over_day_change_rate: '0.0430622009569378',
            as_of_date: '2024-05-10'
        },
        {
            product_id: 'p-102',
            product_name: 'Barrier Toner',
            product_name_source: 'product_master',
            profile_role_primary: 'expansion',
            profile_role_secondary: 'entry',
            profile_confidence: '0.84',
            role_state_primary: '관측 상태 없음',
            role_state_confidence: '',
            pgm_observed_flag: 'false',
            role_state_source: 'blank',
            revenue: '296000',
            order_count: '4',
            quantity: '4',
            revenue_share_in_brand_day: '0.3238512035010941',
            revenue_rank_in_brand_day: '2',
            revenue_7d: '2241000',
            revenue_30d: '2855000',
            revenue_90d: '2855000',
            revenue_day_over_day_change_rate: '-0.019867549668874173',
            as_of_date: '2024-05-10'
        },
        {
            product_id: 'p-103',
            product_name: 'Calm Cleanser',
            product_name_source: 'product_master',
            profile_role_primary: 'return',
            profile_role_secondary: 'return',
            profile_confidence: '0.74',
            role_state_primary: 'return',
            role_state_confidence: '0.72',
            pgm_observed_flag: 'true',
            role_state_source: 'same_date_snapshot',
            revenue: '126000',
            order_count: '2',
            quantity: '2',
            revenue_share_in_brand_day: '0.13785557986870897',
            revenue_rank_in_brand_day: '3',
            revenue_7d: '1037000',
            revenue_30d: '1393000',
            revenue_90d: '1393000',
            revenue_day_over_day_change_rate: '-0.03816793893129771',
            as_of_date: '2024-05-10'
        },
        {
            product_id: 'p-104',
            product_name: 'Night Repair Mask',
            product_name_source: 'order_item_fallback',
            profile_role_primary: '프로필 정보 없음',
            profile_role_secondary: '',
            profile_confidence: '',
            role_state_primary: '관측 상태 없음',
            role_state_confidence: '',
            pgm_observed_flag: 'false',
            role_state_source: 'blank',
            revenue: '56000',
            order_count: '1',
            quantity: '1',
            revenue_share_in_brand_day: '0.061269146608315096',
            revenue_rank_in_brand_day: '4',
            revenue_7d: '347000',
            revenue_30d: '433000',
            revenue_90d: '433000',
            revenue_day_over_day_change_rate: '0.16666666666666666',
            as_of_date: '2024-05-10'
        }
    ],
    product_detail_header: [
        {
            product_id: 'p-101',
            headline: 'Hydra Serum 운영 요약',
            summary: '상품 기준 프로필은 첫구매 유도이며, 기준일 관측 상태는 단골 유도입니다.',
            priority_hint: '왜: 프로필과 기준일 관측 상태가 같은 방향인지 확인해야 운영 신호를 과해석하지 않습니다. 근거: 기준일 매출 436,000원, 7일 누적 2,517,000원. 다음 확인: 매출 흐름과 전환/복귀 신호를 같이 보세요.'
        },
        {
            product_id: 'p-102',
            headline: 'Barrier Toner 운영 요약',
            summary: '상품 기준 프로필은 단골 유도이며, 기준일 관측 상태는 관측 상태 없음입니다. 동일 일자 스냅샷만 사용하므로 다른 날짜 상태로 보정하지 않았습니다.',
            priority_hint: '왜: 프로필은 있어도 기준일 관측 상태가 비면 최근 확정일 해석을 확정하기 어렵습니다. 근거: 동일 일자 스냅샷이 없어 관측 상태 없음으로 유지했고 최신 역할로 보정하지 않았습니다. 다음 확인: 관측 누락 여부, 기준일 매출, 연결 상품 흐름을 순서대로 확인하세요.'
        },
        {
            product_id: 'p-103',
            headline: 'Calm Cleanser 운영 요약',
            summary: '상품 기준 프로필은 반복 구매이며, 기준일 관측 상태도 반복 구매입니다.',
            priority_hint: '왜: 프로필과 기준일 관측 상태가 같은 방향인지 확인해야 운영 신호를 과해석하지 않습니다. 근거: 기준일 매출 126,000원, 7일 누적 1,037,000원. 다음 확인: 매출 흐름과 전환/복귀 신호를 같이 보세요.'
        },
        {
            product_id: 'p-104',
            headline: 'Night Repair Mask 운영 요약',
            summary: '상품 기준 프로필은 프로필 정보 없음이며, 기준일 관측 상태는 관측 상태 없음입니다. 동일 일자 스냅샷만 사용하므로 다른 날짜 상태로 보정하지 않았습니다.',
            priority_hint: '왜: 프로필과 기준일 관측 상태가 모두 비면 운영 해석 근거가 가장 약합니다. 근거: 동일 일자 스냅샷이 없어 관측 상태 없음으로 유지했고 최신 역할로 보정하지 않았습니다. 다음 확인: 관측 누락 여부와 상품 기본 정보 정합성을 먼저 확인하세요.'
        }
    ],
    role_structure_chart: [
        {
            role_state_primary: 'expansion',
            revenue: '436000',
            product_count: '1',
            revenue_share: '0.47702407002188185'
        },
        {
            role_state_primary: '관측 상태 없음',
            revenue: '352000',
            product_count: '2',
            revenue_share: '0.3851203501094092'
        },
        {
            role_state_primary: 'return',
            revenue: '126000',
            product_count: '1',
            revenue_share: '0.13785557986870897'
        }
    ],
    revenue_structure_chart: [
        {
            product_id: 'p-101',
            product_name: 'Hydra Serum',
            revenue: '436000',
            revenue_share_in_brand_day: '0.47702407002188185',
            role_state_primary: 'expansion'
        },
        {
            product_id: 'p-102',
            product_name: 'Barrier Toner',
            revenue: '296000',
            revenue_share_in_brand_day: '0.3238512035010941',
            role_state_primary: '관측 상태 없음'
        },
        {
            product_id: 'p-103',
            product_name: 'Calm Cleanser',
            revenue: '126000',
            revenue_share_in_brand_day: '0.13785557986870897',
            role_state_primary: 'return'
        },
        {
            product_id: 'p-104',
            product_name: 'Night Repair Mask',
            revenue: '56000',
            revenue_share_in_brand_day: '0.061269146608315096',
            role_state_primary: '관측 상태 없음'
        }
    ],
    priority_checks: [
        {
            priority_rank: '1',
            priority: 'medium',
            entity_type: 'product',
            entity_id: 'p-102',
            label: 'Barrier Toner 당일 관측 상태 없음',
            reason: '왜: 매출 상위 상품인데 기준일 역할 관측 상태가 비어 있어 최근 확정일 해석을 확정할 근거가 부족합니다.',
            suggested_check: '다음 확인: PGM 관측 누락 여부, 기준일 매출 기여도, 연결 상품 전환 신호를 차례로 확인하세요.',
            evidence: '근거: revenue.rank=2; revenue.share=0.3238512035010941; role_state_source=blank',
            rule_source: 'revenue_structure_daily.revenue_rank_in_brand_day + product_role_state_daily.role_state_source'
        }
    ],
    transition_summary: [
        {
            product_id: 'p-101',
            product_name: 'Hydra Serum',
            target_product_id: 'p-102',
            target_product_name: 'Barrier Toner',
            transition_rank: '1',
            transition_rate: '0.21',
            avg_days_to_transition: '16.2',
            transition_customer_cnt: '14',
            as_of_date: '2024-05-10'
        }
    ],
    return_loop_summary: [
        {
            product_id: 'p-101',
            product_name: 'Hydra Serum',
            return_case_count: '9',
            qualified_return_rate: '0.18',
            simple_repeat_rate: '0.33',
            return_loop_rate: '0.11',
            avg_return_days: '21.4',
            as_of_date: '2024-05-10'
        }
    ],
    revenue_inflow_context: [
        {
            context_key: 'utm_attributed_order_share_30d',
            label: '최근 30일 UTM 식별 주문 비중',
            value: '0.62',
            detail: '식별 주문 31건 / 전체 50건',
            as_of_date: '2024-05-10'
        },
        {
            context_key: 'top_utm_source_30d',
            label: '상위 유입 source',
            value: 'meta',
            detail: '최근 30일 기여 매출 2,430,000원',
            as_of_date: '2024-05-10'
        }
    ]
};
